name: Regression Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests in Docker
        run: docker-compose up --build --exit-code-from test-runner
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: output-artifacts
          path: output/
